# Generated by Django 5.2.4 on 2025-07-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_chaivarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
